getduy ee

diff --git a/.github/workflows/deploy2.yaml b/.github/workflows/deploy2.yaml
--- a/.github/workflows/deploy2.yaml
+++ b/.github/workflows/deploy2.yaml
@@ -1,94 +1,94 @@
-name: Deploy to EC2
-
-on:
-  push:
-    branches: [ "master" ]
-  pull_request:
-    branches: [ "master" ]
-
-jobs:
-  build:
-    name: Build
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v3.1.0
-        with:
-          gradle-version: '8.9'
-
-      - name: Build gatewayapp with Gradle
-        run: gradle build
-        shell: sh
-        working-directory: ./gatewayapp
-
-      - name: List files in build/libs directory
-        run: ls -l ./gatewayapp/build/libs
-
-      - name: Archive build artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: app-jar
-          path: gatewayapp/build/libs/*.jar
-
-  deploy:
-    name: Deploy
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Download build artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: app-jar
-
-      - name: Setup SSH key
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
-
-      - name: Copy JAR file to EC2
-        run: |
-          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./gatewayapp-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
-
-      - name: Deploy and restart service on EC2
-        uses: appleboy/ssh-action@v0.1.7
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            echo "Updating JAR file and restarting service..."
-            # Check if the new JAR file exists
-            if [ -f /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar ]; then
-              echo "JAR file found, proceeding with deployment."
-              # Stop the service
-              sudo systemctl stop gatewayapp.service
-              # Remove the old JAR file
-              sudo rm -f /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
-              # Move the new JAR file to the correct location
-              sudo mv /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
-              # Reload and restart the service
-              sudo systemctl daemon-reload
-              sudo systemctl start gatewayapp.service
-              # Check the status of the service
-              sudo systemctl status gatewayapp.service
-            else
-              echo "JAR file not found. Deployment failed."
-              exit 1
-            fi
+#name: Deploy to EC2
+#
+#on:
+#  push:
+#    branches: [ "master" ]
+#  pull_request:
+#    branches: [ "master" ]
+#
+#jobs:
+#  build:
+#    name: Build
+#    runs-on: ubuntu-latest
+#    permissions:
+#      contents: read
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: '17'
+#          distribution: 'temurin'
+#
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v3.1.0
+#        with:
+#          gradle-version: '8.9'
+#
+#      - name: Build gatewayapp with Gradle
+#        run: gradle build
+#        shell: sh
+#        working-directory: ./gatewayapp
+#
+#      - name: List files in build/libs directory
+#        run: ls -l ./gatewayapp/build/libs
+#
+#      - name: Archive build artifacts
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: app-jar
+#          path: gatewayapp/build/libs/*.jar
+#
+#  deploy:
+#    name: Deploy
+#    runs-on: ubuntu-latest
+#    needs: build
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Download build artifacts
+#        uses: actions/download-artifact@v2
+#        with:
+#          name: app-jar
+#
+#      - name: Setup SSH key
+#        run: |
+#          mkdir -p ~/.ssh
+#          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
+#          chmod 600 ~/.ssh/id_rsa
+#        env:
+#          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
+#
+#      - name: Copy JAR file to EC2
+#        run: |
+#          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./gatewayapp-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
+#
+#      - name: Deploy and restart service on EC2
+#        uses: appleboy/ssh-action@v0.1.7
+#        with:
+#          host: ${{ secrets.EC2_HOST }}
+#          username: ${{ secrets.EC2_USER }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script: |
+#            echo "Updating JAR file and restarting service..."
+#            # Check if the new JAR file exists
+#            if [ -f /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar ]; then
+#              echo "JAR file found, proceeding with deployment."
+#              # Stop the service
+#              sudo systemctl stop gatewayapp.service
+#              # Remove the old JAR file
+#              sudo rm -f /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
+#              # Move the new JAR file to the correct location
+#              sudo mv /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
+#              # Reload and restart the service
+#              sudo systemctl daemon-reload
+#              sudo systemctl start gatewayapp.service
+#              # Check the status of the service
+#              sudo systemctl status gatewayapp.service
+#            else
+#              echo "JAR file not found. Deployment failed."
+#              exit 1
+#            fi
